import pyodbc
import pandas as pd
import numpy as np
import random
import sqlalchemy as sal
from sqlalchemy import create_engine, inspect, text
from urllib.parse import quote_plus

CAMINHO = 'C:\\Users\\Pichau\\Downloads\\FGVENERGIA\\'

# CRIANDO UM MAILING PARA WEBINAR

## 1. CONECTANDO AO SQL SERVER E AO BANCO DE DADOS
username = 'FGV_AIRFLOW_USER'
password = 'airflow2022'

server_1 = 'SQLDC1VPR0002'
database_1 = 'FGV_DICOM_MDM_ACADEMICO'

# parametros de banco de dados
server_2 = 'SQLDC1VPR0002'
database_2 = 'FGV_DICOM_DBM'

# transformando para formato odbc
parametros_1 = ('DRIVER={SQL Server};SERVER=' + server_1 + ';PORT=4513;DATABASE=' + database_1 + ';ENCRYPT=no;TrustServerCertificate=yes;UID=' + username + ';PWD=' + password)

# transformando para formato odbc

parametros_2 = ('DRIVER={SQL Server};SERVER=' + server_2 + ';PORT=4513;DATABASE=' + database_2 + ';ENCRYPT=no;TrustServerCertificate=yes;UID=' + username + ';PWD=' + password)

url_db_1 = quote_plus(parametros_1)
url_db_2 = quote_plus(parametros_2)

# Estabelecendo conexão com o banco de dados
engine_1 = sal.create_engine('mssql+pyodbc:///?odbc_connect=%s' % url_db_1)
engine_2 = sal.create_engine('mssql+pyodbc:///?odbc_connect=%s' % url_db_2)

# Estabelecendo a conexão com o banco de dados usando o mecanismo como interface
con = engine_1.connect()
inspector_1 = inspect(engine_1)

con2 = engine_2.connect()
inspector_2 = inspect(engine_2)

# con = pyodbc.connect(conn_str)
# con2 = pyodbc.connect(conn_str2)

# 2. SELECIONANDO ALUNOS CADASTRO DE INTERESSE

query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT t.SEQ_BUP_PESSOA , o.DES_OFERTA, o.DES_ESCOLA_UNIDADE FROM BUP_TRILHA_PESSOA_DICOM t WITH (NOLOCK) JOIN BIP_PESSOA_PRODUTO_DICOM prod WITH (NOLOCK) ON t.SEQ_STG_PESSOA = prod.SEQ_BIP_PESSOA JOIN BIP_PESSOA_PRODUTO_OFERTA_DICOM o WITH (NOLOCK) ON prod.SEQ_BIP_PESSOA_PRODUTO = o.SEQ_BIP_PESSOA_PRODUTO  WHERE (o.COD_CURRICULO NOT LIKE '%OCW%') -- CURSOS GRATUITOS (OCW) AND (o.DES_OFERTA LIKE '%LEI%' OR o.DES_OFERTA LIKE '%DIREITO%' OR o.DES_OFERTA LIKE '%JURIDIC%' OR o.DES_OFERTA LIKE '%TRIBUT%') AND (o.DTH_INICIO_OFERTA <= '2020-10-05')"

INTERESSE = pd.read_sql(text(query), con)
## SELECIONANDO UMA AMOSTRA DE ALUNOS CADASTRO DE INTERESSE
INTERESSE_SAMPLE = random.sample(list(INTERESSE['SEQ_BUP_PESSOA']), k=int(0.5 * len(INTERESSE['SEQ_BUP_PESSOA'])))
INTERESSE_SAMPLE = pd.DataFrame(INTERESSE_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 1')

## 2. SELECIONANDO ALUNOS DE CURSOS GRATUITOS (OCW) COM TEMAS RELACIONADOS

query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT t.SEQ_BUP_PESSOA FROM BUP_TRILHA_PESSOA_DICOM t WITH (NOLOCK) JOIN BIP_PESSOA_PRODUTO_DICOM prod WITH (NOLOCK) ON t.SEQ_STG_PESSOA = prod.SEQ_BIP_PESSOA JOIN BIP_PESSOA_PRODUTO_OFERTA_DICOM o WITH (NOLOCK) ON prod.SEQ_BIP_PESSOA_PRODUTO = o.SEQ_BIP_PESSOA_PRODUTO WHERE (o.COD_CURRICULO LIKE '%OCW%') AND (o.DES_OFERTA LIKE '% LEI %' OR o.DES_OFERTA LIKE '%DIREITO%' OR o.DES_OFERTA LIKE '%JURIDIC%' OR o.DES_OFERTA LIKE '%TRIBUT%')"

OCW = pd.read_sql(text(query), con)

# SELECIONANDO UMA AMOSTRA DOS ALUNOS OCW
OCW_SAMPLE = random.sample(list(OCW['SEQ_BUP_PESSOA']), k=int(0.2*len(OCW['SEQ_BUP_PESSOA'])))
OCW_SAMPLE = pd.DataFrame(OCW_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 2')

# Selecionando alunos de eventos com temas relacionados
query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT t.SEQ_BUP_PESSOA , e.* FROM BUP_TRILHA_PESSOA_DICOM t, BIP_PESSOA_PRODUTO_DICOM prod, BIP_PESSOA_PRODUTO_EVENTO_DICOM e (NOLOCK) WHERE (t.SEQ_STG_PESSOA = prod.SEQ_BIP_PESSOA) AND (prod.SEQ_BIP_PESSOA_PRODUTO = e.SEQ_BIP_PESSOA_PRODUTO) AND (e.NOM_EVENTO LIKE '% LEI %' OR e.NOM_EVENTO LIKE '%DIREITO%' OR e.NOM_EVENTO LIKE '%JURIDIC%' OR e.NOM_EVENTO LIKE '%TRIBUT%')"

EVENTOS = pd.read_sql(text(query), con)

# Selecionando uma amostra aleatória dos alunos de eventos
EVENTOS_SAMPLE = random.sample(list(EVENTOS['SEQ_BUP_PESSOA']), k=int(0.8 * len(EVENTOS['SEQ_BUP_PESSOA'])))
EVENTOS_SAMPLE = pd.DataFrame(EVENTOS_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 3')

# 4. SELECIONANDO ALUNOS COM CARGOS RELACIONADOS AO WEBINAR
query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT emp.SEQ_BUP_PESSOA , emp.* FROM BUP_PESSOA_EMPREGO_DICOM emp (NOLOCK) WHERE (emp.NOM_EMPRESA NOT LIKE '%FUNDACAO GETULIO VARGAS%' AND emp.NOM_EMPRESA NOT LIKE '%VARGAS%' AND emp.NOM_EMPRESA NOT LIKE '%FGV%' AND emp.NOM_EMPRESA NOT LIKE '%AVON%' AND emp.NOM_EMPRESA NOT LIKE '%BRADESCO%')  AND (emp.DES_CARGO LIKE '%ADVOGAD%' OR emp.DES_CARGO LIKE '%JUIZ%' OR emp.DES_CARGO LIKE '%DESEMBARGAD%' OR emp.DES_FUNCAO LIKE '%ADVOGAD%' OR emp.DES_FUNCAO LIKE '%JUIZ%' OR emp.DES_FUNCAO LIKE '%DESEMBARGAD%' )"

CARGO = pd.read_sql(text(query), con)

# SELECIONANDO UMA AMOSTRA DOS ALUNOS COM CARGOS RELACIONADOS
CARGO_SAMPLE = random.sample(list(EVENTOS['SEQ_BUP_PESSOA']), k=int(1 * len(EVENTOS['SEQ_BUP_PESSOA'])))
CARGO_SAMPLE = pd.DataFrame(CARGO_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 4')

# 5. SELECIONANDO ALUNOS COM FORMACAO RELACIONADOS AO WEBINAR
query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT fa.SEQ_BUP_PESSOA FROM BUP_PESSOA_FORMACAO_ACADEMICA_DICOM fa (NOLOCK) WHERE (fa.DES_GRANDE_AREA LIKE '%DIREITO%' OR fa.DES_GRANDE_AREA LIKE '%JURIDIC%' OR fa.DES_GRANDE_AREA LIKE '%TRIBUT%')"

FORMACAO = pd.read_sql(text(query), con)

# SELECIONANDO UMA AMOSTRA DOS ALUNOS COM CARGOS RELACIONADOS
FORMACAO_SAMPLE = random.sample(list(FORMACAO['SEQ_BUP_PESSOA']), k=int(0.5 * len(FORMACAO['SEQ_BUP_PESSOA'])))
FORMACAO_SAMPLE = pd.DataFrame(FORMACAO_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 5')

# 6. SELECIONANDO ALUNOS DE CURSOS PAGOS DA FGV

query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT T.SEQ_BUP_PESSOA , NOM_CURSO, STA_SITUACAO FROM BUP_TRILHA_PESSOA_DICOM t INNER JOIN BIP_PESSOA_DICOM bipP ON T.SEQ_STG_PESSOA = BIPP.SEQ_STG_PESSOA INNER JOIN BIP_PESSOA_PRODUTO_DICOM prod ON BIPP.SEQ_BIP_PESSOA = PROD.SEQ_BIP_PESSOA INNER JOIN BIP_PESSOA_PRODUTO_CURSO_DICOM c ON C.SEQ_BIP_PESSOA_PRODUTO = PROD.SEQ_BIP_PESSOA_PRODUTO LEFT OUTER JOIN BUP_PESSOA_EMPREGO_DICOM emp ON EMP.SEQ_BUP_PESSOA = T.SEQ_BUP_PESSOA WHERE(c.FLG_CUMPRIMENTO <> 'S' or c.FLG_CUMPRIMENTO is null) AND c.COD_CURRICULO NOT LIKE '%OCW%' AND ((emp.NOM_EMPRESA NOT LIKE '%FUNDACAO GETULIO VARGAS%' AND emp.NOM_EMPRESA NOT LIKE '%VARGAS%' AND emp.NOM_EMPRESA NOT LIKE '%FGV%' and emp.NOM_EMPRESA NOT LIKE '%AVON%' AND emp.NOM_EMPRESA NOT LIKE '%BRADESCO%') or emp.NOM_EMPRESA is null) AND (c.NOM_CURSO LIKE '%DIREITO%' OR c.NOM_CURSO LIKE '%JURIDC%'  OR c.NOM_CURSO LIKE '%LEI%' OR c.NOM_CURSO LIKE '%TRIBUT%')"

EXALUNOS = pd.read_sql(text(query), con)

# SELECIONANDO UMA AMOSTRA DOS ALUNOS
EXALUNOS_SAMPLE = random.sample(list(EXALUNOS['SEQ_BUP_PESSOA']), k=int(1 * len(EXALUNOS['SEQ_BUP_PESSOA'])))
EXALUNOS_SAMPLE = pd.DataFrame(EXALUNOS_SAMPLE, columns=['SEQ_BUP_PESSOA'])

print('passou aqui 6')

# 7. JUNTANDO DATA FRAMES E DEIXANDO SOMENTE DISTINTOS
BUPS_INICIAL = pd.concat([INTERESSE_SAMPLE, OCW_SAMPLE, EVENTOS_SAMPLE, CARGO_SAMPLE, FORMACAO_SAMPLE, EXALUNOS_SAMPLE])
BUPS_INICIAL_DISTINTOS = BUPS_INICIAL.drop_duplicates()


# 8. EXCLUSÃO ALUNO VIGENTE
query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT t.SEQ_BUP_PESSOA , c.* FROM BUP_TRILHA_PESSOA_DICOM t WITH (NOLOCK) JOIN BIP_PESSOA_PRODUTO_DICOM prod WITH (NOLOCK) ON t.SEQ_STG_PESSOA = prod.SEQ_BIP_PESSOA JOIN BIP_PESSOA_PRODUTO_CURSO_DICOM c WITH (NOLOCK) ON prod.SEQ_BIP_PESSOA_PRODUTO = c.SEQ_BIP_PESSOA_PRODUTO WHERE (c.FLG_CUMPRIMENTO <> 'S' OR c.FLG_CUMPRIMENTO IS NULL) -- N�O PEGAR PESSOAS QUE EST�O CURSANDO ALGUMA DISCIPLINA AND c.COD_CURRICULO NOT LIKE '%OCW%' -- EX-ALUNOS DE CURSOS QUE N�O S�O GRATUITOS   AND (c.STA_SITUACAO = 'MATRICULADO' AND c.DTH_FIM_CURSO IS NULL)  OR (c.DES_ESCOLA_UNIDADE LIKE '%FGVCORPSP00%' or c.DES_ESCOLA_UNIDADE LIKE '%ONLINECORP%' or c.DES_ESCOLA_UNIDADE  LIKE '%CONSULTING%')"

VIGENTES = pd.read_sql(text(query), con)

EXCLUSAO_1 = pd.merge(BUPS_INICIAL_DISTINTOS, VIGENTES, on='SEQ_BUP_PESSOA', how='outer', indicator=True)
EXCLUSAO_1 = EXCLUSAO_1[EXCLUSAO_1['_merge'] == 'left_only'].drop(columns=['_merge'])

print('passou aqui 7')

# 9. SELECIONANDO PESSOAS DE 25 A 50 ANOS

query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT f.SEQ_BUP_PESSOA, YEAR(f.DTH_NASCIMENTO) AS ANO_NASC FROM BUP_PESSOA_FISICA_DICOM f WHERE YEAR(f.DTH_NASCIMENTO) < 1972 OR YEAR(f.DTH_NASCIMENTO) > 1997"

IDADE = pd.read_sql(text(query), con)

EXCLUSAO_2 = pd.merge(EXCLUSAO_1, IDADE, on="SEQ_BUP_PESSOA", how="left", indicator=True)
EXCLUSAO_2 = EXCLUSAO_2[EXCLUSAO_2['_merge'] == 'left_only']
EXCLUSAO_2 = EXCLUSAO_2.drop(columns=['_merge'])

# 10. EXCLUINDO ESTRANGEIROS

query = "SET QUERY_GOVERNOR_COST_LIMIT 0  SELECT DISTINCT E.SEQ_BUP_PESSOA  FROM BUP_ESTRANGEIRO E"

ESTRANGEIROS = pd.read_sql(text(query), con)

BUPS_SEMI_FINAL = pd.merge(EXCLUSAO_2, ESTRANGEIROS, on="SEQ_BUP_PESSOA", how='left', indicator=True)
BUPS_SEMI_FINAL = BUPS_SEMI_FINAL[BUPS_SEMI_FINAL['_merge'] == 'left_only']
BUPS_SEMI_FINAL = BUPS_SEMI_FINAL.drop(columns=['_merge'])


# 11. CONTROLE DE MAILING (EXCLUSÃO BUPS JÁ IMPACTADOS NA SEMANA)
# EXCLUIR TAMBÉM PESSOAS COM MAILING DO MESMO DIA

query = "SET QUERY_GOVERNOR_COST_LIMIT 0  SELECT DISTINCT b.BUP_NEW_281221 , m.Data_Mailing FROM Controle_Mailing_Novo m join FGV_DICOM_MDM_ACADEMICO.dbo.DE_PARA_BUPS_FINAL_281221 b ON m.HASH=b.HASH_NEW_281221 WHERE m.Data_Mailing >= '2022-10-17'"

QUERY_BUPS_SEMANA = pd.read_sql(text(query), con2)

QUERY_BUPS_SEMANA.rename(columns={"BUP_NEW_281221": "SEQ_BUP_PESSOA"}, inplace=True)

BUPS_SEMI_FINAL_1 = pd.merge(BUPS_SEMI_FINAL, QUERY_BUPS_SEMANA, on="SEQ_BUP_PESSOA", how="outer", indicator=True)
BUPS_SEMI_FINAL_1 = BUPS_SEMI_FINAL_1[BUPS_SEMI_FINAL_1["_merge"] == "left_only"].drop(columns=["_merge"])


# EXCLUIR TAMBÉM PESSOAS QUE RECEBERAM MAILING NO MES ANTERIOR

query = "SET QUERY_GOVERNOR_COST_LIMIT 0 SELECT DISTINCT b.BUP_NEW_281221, m.Data_Mailing FROM Controle_Mailing_Novo m join FGV_DICOM_MDM_ACADEMICO.dbo.DE_PARA_BUPS_FINAL_281221 b ON m.HASH=b.HASH_NEW_281221 WHERE m.Data_Mailing >= '2022-09-17'"

BUPS_MES_ANTERIOR = pd.read_sql(text(query), con2)

BUPS_MES_ANTERIOR.rename(columns={"BUP_NEW_281221": "SEQ_BUP_PESSOA"}, inplace=True)

BUPS_SEMI_FINAL_2 = pd.merge(BUPS_SEMI_FINAL_1, BUPS_MES_ANTERIOR, on="SEQ_BUP_PESSOA", how="outer")
BUPS_SEMI_FINAL_2["SEQ_BUP_PESSOA"] = BUPS_SEMI_FINAL_2["SEQ_BUP_PESSOA"].astype(str)

# 12.SELECIONAR AMOSTRA FINAL (SE NECESSÁRIO)

BUPS_FINAL = np.random.choice(BUPS_SEMI_FINAL_2["SEQ_BUP_PESSOA"], size=int(0.42 * len(BUPS_SEMI_FINAL_2["SEQ_BUP_PESSOA"])), replace=False)
BUPS_FINAL = pd.DataFrame(BUPS_FINAL, columns=["SEQ_BUP_PESSOA"])

# 13. INCLUINDO COLUNA COM O NOME DA TAREFA

BUPS_FINAL["TAREFA"] = "TAREFA53934_DIREITO_SP_Capital_Market_Talks_Regulacao_para_proteger_investidores_e_desenvolver_a_criptoeconomia_OUT22"

#Fechando conexão com banco
con.close()
con2.close()

## 14. EXPORTAÇÃO ENVIO PARA A TIC

BUPS_FINAL.to_csv(CAMINHO + 'TAREFA53934_DIREITO_SP_Capital_Market_Talks_Regulacao_para_proteger_investidores_e_desenvolver_a_criptoeconomia_MAR2023.csv', index=False, quoting=False)
